[package]
name = "diesel_json_logic_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
diesel_json_logic_macro_rules = { path = "../diesel-json-logic-macro-rules" }
proc-macro2 = "1.0"
quote = "1.0.37"
syn = "2.0.77"
